spring:
  application:
    name: doodle

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.sql

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

kind: Application

